### ISSUE TITLE
Is there anyway to get the element class name?

### ISSUE THREAD

**Issue by michael-caffrey** [atheriel/accessibility#5]
I seriously can't thank you enough for making this. It has saved me a tremendous amount of time. I'm not too familiar with Objective-C, but is there anyway to retrieve the element class name? I attached an example from the Accessibility Inspector GUI https://imgur.com/ySZirRA Here the Element Class is CalcWindow. Is there anyway to get this? Figured it would be significantly easier to find children along the hierarchy.

**Comment by atheriel** [comment]
I'm happy to hear that it's helped you out. Unfortunately, it's a bit hard for me to answer specific questions, since (1) I wrote this five years ago; and (2) I no longer own any Mac hardware to test it on.

A guess: does the class show up in the `.keys()`?

Otherwise, I'm not sure if I can be all that helpful. The underlying CoreFoundation library documentation seems to be [here](https://developer.apple.com/documentation/applicationservices/axuielement_h?language=objc). If it is possible in that C code, it should be possible to make this package do it, possibly with a patch.

**Comment by michael-caffrey** [comment]
@atheriel thanks for the supply. I dug around, and found out that you cannot do it. It appears that the accessibility inspector has some special entitlements. Oh well. https://stackoverflow.com/questions/45590888/how-to-get-the-objective-c-class-name-corresponding-to-an-axuielement

**Comment by atheriel** [comment]
Good detective work. I will close this for now, since there seems to be no solution.

**Comment by michael-caffrey** [comment]
Thanks, hopefully this will save someone a few hours trying to find a solution.
